parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - plugin:react-hooks/recommended
  - plugin:jsx-a11y/recommended
  - prettier
plugins:
  - '@typescript-eslint'
  - react
  - react-hooks
  - jsx-a11y

env:
  browser: true
  node: true
  es2021: true
settings:
  react:
    version: detect
rules:
  react/react-in-jsx-scope: off
  react/prop-types: off
  react/jsx-uses-react: off
  react/jsx-uses-vars: error
  '@typescript-eslint/explicit-module-boundary-types': off
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: '^_'
      varsIgnorePattern: '^_'
overrides:
  - files: ['**/*.tsx']
    rules:
      react/jsx-filename-extension:
        - error
        - extensions: ['.tsx']
