name: Audit

on:
  push:
    branches:
      - '**'

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add required Linux dependencies
        uses: ./.github/actions/linux-deps

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ hashFiles('**/yarn.lock') }}

      # - name: Audit dependencies
      # Disabled until we can update electron
      # run: yarn audit
