name: Exact versions

on:
  push:
    branches:
      - '**'
jobs:
  check-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Add @actions/core
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 120
          max_attempts: 3
          retry_on: error
          command: yarn add @actions/core --ignore-scripts -E

      - name: Check exact versions
        uses: ./.github/actions/check-version-lock
