name: Typecheck

on:
  push:
    branches:
      - '**'
jobs:
  typecheck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Add required Linux dependencies
        uses: ./.github/actions/linux-deps

      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_seconds: 240
          max_attempts: 3
          retry_on: error
          command: yarn
        env:
          STX_NETWORK: testnet

      - name: Check types
        run: yarn tsc --noEmit
